### ISSUE TITLE
Add PictureLayerMechanism

### ISSUE THREAD

**Issue by LirycMoaners** [LirycMoaners/city-key#20]
It shows the user camera with a layer on it which show a picture in 50% opacity.
The goal for the user is to find the same image with his camera.

An image recognition module should be added to the projet => to discuss

**Comment by FeliciaMarlove** [comment]
Really difficult in usage because any change in the area (eg a temporary fair, works...) could prevent the user from standing at the exact place they need to stand (different angle), therefore the app wouldn't be able to recognize the scene (image comparison would require exact same framing from exact same angle and distance I guess?)

**Comment by FeliciaMarlove** [comment]
- http://rembrandtjs.com/
- https://www.npmjs.com/package/imagediff (demo http://humblesoftware.github.io/js-imagediff/ )
- https://www.npmjs.com/package/resemblejs
- tensorflow ?
- https://github.com/mapbox/pixelmatch

**Comment by LirycMoaners** [comment]
I found this module : https://rsmbl.github.io/Resemble.js/. It's pretty good for what we want to do. I tested it with the same image image at noon and evening and the similarity is always better than 70%. It's actually the same if it's not perfectly centered. I know that it wont works if the place where the photo has been taken change or if there is an event that prevent the user to be on the good spot. But it's pretty rare and if it's a photo of a small statue or a metal plate, it will always be accessible.
